function [SpinX, SpinY, SpinZ] = auxil_SpinState_PixelMean(SPINSTATE, BOXPARA)

Spin_curr = SPINSTATE.SpinX;
Spin_curr = reshape(Spin_curr,...
    BOXPARA.PosXNum,...
    BOXPARA.PosYNum,...
    BOXPARA.PosZNum,...
    BOXPARA.B0Num,...
    BOXPARA.B1Num,...
    BOXPARA.T1Num,...
    BOXPARA.T2Num);
Spin_mean = mean(mean(mean(Spin_curr, 1), 2), 3);
SpinX = Spin_mean;

Spin_curr = SPINSTATE.SpinY;
Spin_curr = reshape(Spin_curr,...
    BOXPARA.PosXNum,... 
    BOXPARA.PosYNum,...
    BOXPARA.PosZNum,...
    BOXPARA.B0Num,...
    BOXPARA.B1Num,...
    BOXPARA.T1Num,...
    BOXPARA.T2Num);
Spin_mean = mean(mean(mean(Spin_curr, 1), 2), 3);
SpinY = Spin_mean;

Spin_curr = SPINSTATE.SpinZ;
Spin_curr = reshape(Spin_curr,...
    BOXPARA.PosXNum,...
    BOXPARA.PosYNum,...
    BOXPARA.PosZNum,...
    BOXPARA.B0Num,...
    BOXPARA.B1Num,...
    BOXPARA.T1Num,...
    BOXPARA.T2Num);
Spin_mean = mean(mean(mean(Spin_curr, 1), 2), 3);
SpinZ = Spin_mean;

end